name: Deploy KnotPerfect-backEnd

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t staypermissionless4/knotperfect-backend:latest .

      - name: Publish Image to Docker Hub
        run: docker push staypermissionless4/knotperfect-backend:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Remove old Docker images (except latest)
        run: docker images -q staypermissionless4/knotperfect-backend | xargs -r docker rmi -f

      - name: Pull image from Docker Hub
        run: docker pull staypermissionless4/knotperfect-backend:latest

      - name: Delete old container (if exists)
        run: |
          docker rm -f knotperfect-backend-container || true

      - name: Run Docker Container
        run: |
          docker run -d -p 5555:5555 --name knotperfect-backend-container \
            -e MONGO_PASSWORD="${{ secrets.MONGO_PASSWORD }}" \
            staypermissionless4/knotperfect-backend:latest
